# Site settings
title: WebFólio José Pedro
description: A blog about lorem ipsum dolor sit amet
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: José Pedro
user_description: 
user_title: Web Developer
email: jose.coelho@usp.br
github_username:  JPedroBiosystems


# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
